services:
  web:
    build: .
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html:rw
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./apache/httpd.conf:/etc/apache2/httpd.conf:ro
    ports:
      - "7890:80"
    networks:
      - network
    depends_on:
      - mariadb
    environment:
      - UID=1000
      - GID=1000
      - ADMIN_PASSWORD=stopwithit
      - CJ_USERNAME=vidlii
      - CJ_PASSWORD=vidlii
      - DB_HOST=mariadb
      - DB_DATABASE=vidlii
      - DB_USER=root
      - DB_PASSWORD=vidlii
      - DB_CHARSET=latin1
      - CSS_FILE=/css/m.css?8
      - PROFILE_CSS_FILE=/css/profile.css?5
      - COSMIC_CSS_FILE=/css/cosmicpanda.css?5
      - PROFILE_JS_FILE=/js/profile.js?9
      - COSMIC_JS_FILE=/js/cosmicpanda.js?3
      - MAIN_JS_FILE=/js/main3.js?22


  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: vidlii
      MYSQL_DATABASE: vidlii
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: vidlii
    ports:
      - "7891:80"
    networks:
      - network
    depends_on:
      - mariadb

networks:
  network:
    driver: bridge

